###########################################
#                                         #
#            MINESX CONFIG                #
#                                         #
###########################################

#GLOBAL MINE RESET EVENT
mines:
  - test
  - test2
reset-interval: 60